packages: []
allowBuilds:
  esbuild: true
  msw: true
  sharp: false
  unrs-resolver: false
  workerd: true
verifyDepsBeforeRun: install
engineStrict: true
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
