packages: []
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true
verifyDepsBeforeRun: install
engineStrict: true
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
overrides:
  'brace-expansion@>=5.0.0 <5.0.6': 5.0.6
  fast-uri: 3.1.2
  fast-xml-builder: 1.1.7
  fast-xml-parser: 5.7.0
  hono: 4.12.23
  ip-address: 10.1.1
  postcss: ^8.5.15
  qs: 6.15.2
  vite: ^8.0.16
peerDependencyRules:
  allowedVersions:
    typescript: '>=6 <6.1'
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.8.16'
  - '@eslint-react/core@5.8.16'
  - '@eslint-react/eslint-plugin@5.8.16'
  - '@eslint-react/eslint@5.8.16'
  - '@eslint-react/jsx@5.8.16'
  - '@eslint-react/shared@5.8.16'
  - '@eslint-react/var@5.8.16'
  - eslint-plugin-react-dom@5.8.16
  - eslint-plugin-react-jsx@5.8.16
  - eslint-plugin-react-naming-convention@5.8.16
  - eslint-plugin-react-rsc@5.8.16
  - eslint-plugin-react-web-api@5.8.16
  - eslint-plugin-react-x@5.8.16
